export const types = Object.freeze({
    // Sync
    INITIALIZE:        'INITIALIZE',
    START_FETCHING:    'START_FETCHING',
    STOP_FETCHING:     'STOP_FETCHING',
    SET_MEDICINES:     'SET_MEDICINES',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    ADD_MEDICINE:      'ADD_MEDICINE',
    DELETE_MEDICINE:   'DELETE_MEDICINE',
    EDIT_MEDICINE:     'EDIT_MEDICINE',
    UPDATE_MEDICINE:   'UPDATE_MEDICINE',
});
