export const types = Object.freeze({
    // Async
    INITIALIZE_ASYNC: 'INITIALIZE_ASYNC',

    // Sync
    INITIALIZE:        'INITIALIZE',
    START_FETCHING:    'START_FETCHING',
    STOP_FETCHING:     'STOP_FETCHING',
    SET_ONLINE_STATE:  'SET_ONLINE_STATE',
    SET_OFFLINE_STATE: 'SET_OFFLINE_STATE',
    SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
    SET_USER_LANGUAGE: 'SET_USER_LANGUAGE',
    AUTHENTICATE:      'AUTHENTICATE',
});
